[package]
name = "distance_between_lat_lng"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
haversine = "0.2.1"
